# SPDX-License-Identifier: Apache-2.0
# © 2026 SZL Holdings. Build + push the killinchu container image to GHCR and
# sign it with cosign (keyless, GitHub OIDC + Fulcio + Rekor).
# Commit DCO-signed: git commit -s -m "ci(killinchu): add build-uds-image workflow"
name: build-uds-image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'image tag'
        required: true
        default: 'uds-v0.2.0'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: .
          push: true
          tags: ghcr.io/szl-holdings/${{ github.event.repository.name }}:${{ inputs.tag }}
      - uses: sigstore/cosign-installer@053f9b74638557590800a301da1ba82351507e2c # v3.8.1
      - name: cosign sign
        run: cosign sign --yes ghcr.io/szl-holdings/${{ github.event.repository.name }}:${{ inputs.tag }}
        env:
          COSIGN_EXPERIMENTAL: "1"
